spring:
  application:
    name: najda-backend
    
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
      
  supabase:
    storage:
      bucket: incident-media

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 25MB